/**
 * package mabis.mvc.view.utilities in MABIS
 * by kornicameister
 */
package mvc.view.utilities;

import java.awt.Color;
import java.awt.Dimension;

import javax.swing.JLabel;

/**
 * This is the JLabel based class that provides status bar functionality
 * 
 * @author kornicameister
 * @see http
 *      ://www.java-tips.org/java-se-tips/javax.swing/creating-a-status-bar.html
 */
public class StatusBar extends JLabel {

	/**
	 * The value of this constant is {@value} and it was autogenerated
	 */
	private static final long serialVersionUID = 6160242403078374821L;

	/**
	 * Wrapper for JLabel default constructor extended with Dimension arg
	 * 
	 * @see JLabel#JLabel()
	 */
	public StatusBar() {
		super();
		setMinimumSize(new Dimension(500, 20));
		setPreferredSize(new Dimension(500, 20));
		setMaximumSize(new Dimension(500, 20));
		setMessage("StatusBar ready");
	}

	/**
	 * Wrapper for JLabel String,Alignment constructor
	 * 
	 * @param text
	 *            init message
	 * @param horizontalAlignment
	 * @see JLabel#JLabel(String, int)
	 */
	public StatusBar(String text, int horizontalAlignment) {
		super(text, horizontalAlignment);
		setMinimumSize(new Dimension(500, 20));
		setPreferredSize(new Dimension(500, 20));
		setMaximumSize(new Dimension(500, 20));
		setMessage(text);
	}

	/**
	 * Wrapper for JLabel String constructor
	 * 
	 * @param text
	 *            init message
	 * @see JLabel#JLabel(String)
	 */
	public StatusBar(String text) {
		super(text);
		setMinimumSize(new Dimension(500, 20));
		setPreferredSize(new Dimension(500, 20));
		setMaximumSize(new Dimension(500, 20));
		setMessage(text);
	}

	public void setMessage(String string) {
		this.setForeground(Color.black);
		this.setText(" " + string);
	}

	public void setError(String err) {
		this.setForeground(Color.red);
		this.setText(" " + err);
	}

}
